name: iOS CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build iOS Framework
        run: ./gradlew :composeApp:linkDebugFrameworkIos

      - name: Create IPA file
        run: |
          mkdir -p output/ios
          xcodebuild -workspace composeApp.xcworkspace -scheme composeApp -configuration Debug -destination 'generic/platform=iOS' -sdk iphoneos BUILD_LIBRARY_FOR_DISTRIBUTION=YES CODE_SIGN_IDENTITY="iPhone Developer" CODE_SIGN_IDENTITY_BUILD_SETTING="iPhone Developer" PROVISIONING_PROFILE="Your Provisioning Profile UUID" -export-archive -archivePath "output/ios/app.xcarchive" -exportOptionsPlist exportOptions.plist

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: KloudIOS
          path: output/ios/app.xcarchive
